version: 2.1
jobs:
  test: 
    docker:
        - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Test
          command: echo Test OK!

  deploy:
    parameters:
      region:
        type: enum
        enum: 
          - "EU"
          - "US"
          - "RU"
          - "EN"
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, << parameters.region >>.

workflows:
  build-and-deploy:
    jobs:
      - test
      - build:
          name: "Build EU"
          region: "EU"
          requires:
            - test

      - hold-US: 
          type: approval
          requires:
            - "Build EU"

      - build:
          name: "Build US"        
          requires:
            - "hold-US"
          region: "US"

      - hold-RU: 
          type: approval
          requires:
            - "Build US"

      - build:
          requires:
            - "hold-RU"
          region: "RU"




