version: 2.1

executors:
  my-executor:
    docker:
      - image: debian:stretch

commands:
  deploy:
    parameters:
      region:
        type: enum
        enum: 
          - "EU"
          - "US"
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, << parameters.region >>.
      - run:
          name: Print the Current Time
          command: date

jobs:
  build-EU:
    executor: my-executor
    steps:
      - deploy


workflows:
  build-and-deploy:
    jobs:
      - build-EU:
          region: "EU"


