defaults: &defaults
  parameters:
    region:
      type: enum
      enum: 
        - "EU"
        - "US"
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, << parameters.region >>.

      - run:
          name: Print the Current Time
          command: date


version: 2.1
jobs:
  build_EU:
    <<: *defaults
  build_US:
    <<: *defaults

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_EU:
          region: "EU"
      - build_US:
          type: approval
          requires:
            - "build_EU"
          region: "US"


