version: 2.1
jobs:
  build:
    parameters:
      region:
        type: enum
        enum: 
          - "EU"
          - "US"
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, << parameters.region >>.

      - run:
          name: Print the Current Time
          command: date
          
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          name: "Build EU"
          region: "EU"
      - build:
          name: "Build US" 
          type: approval
          requires:
            - "Build EU"
          region: "US"


