version: 2.1

commands:
  deploy:
    parameters:
      region:
        type: enum
        enum: 
          - "EU"
          - "US"
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, << parameters.region >>.
      - run:
          name: Print the Current Time
          command: date

jobs:
  build-EU:
    docker:
      - image: debian:stretch
    steps:
      - deploy
  build-US:
    docker:
      - image: debian:stretch
    steps:
      - deploy

workflows:
  build-and-deploy:
    jobs:
      - build-EU:
          region: "EU"
      - build-US:
          type: approval
          requires:
            - build-EU
          region: "US"


