defaults: &defaults
  parameters:
    region:
      type: enum
      enum: 
        - "EU"
        - "US"
  docker:
    - image: debian:stretch

  steps:
    - checkout

    - run:
        name: Greeting
        command: echo Hello, << parameters.region >>.

    - run:
        name: Print the Current Time
        command: date


version: 2.1
jobs:
  build-EU:
    <<: *defaults
  build-US:
    <<: *defaults

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build-EU:
          region: "EU"
      - build-US:
          type: approval
          requires:
            - build-EU
          region: "US"


